export const chakras = [
  {
    name: "Root Chakra",
    image: "image/root.png",
    visualimage: "image/Recraft/Root/sense-of-smell-smelling-elixir-.png",
    visualname: "Sense of smell",
    mantra: "Lam",
    audio: "audio/Lam.aac",
    location: "base of your spine",
    associated:"Sense of Smell, Sense Of Security, Stability, Sense of responsibility",
    color: "red",
    colorcode: "#DC143C",
    element: "Earth",
    feature: "Stability",
    description: "The foundation of our being, responsible for our sense of security and stability",
  },
  {
      name: "Sacral chakra",
      image: "image/sacral.png",
      visualimage: "image/Recraft/Sacral/sense-of-pleasure-elixir.png",
      visualname: "Sense of sexuality",
      mantra: "Vam",
      audio: "audio/Vam.aac",
      location: "area below the navel",
      associated:"Sexuality, Sense of taste, Creativity, Emotions",
      color: "orange",
      colorcode: "#FF4500",
      element: "Water",
      feature: "Creativity",
      description: "The center of our creativity, sexuality, and emotions",
    },
    {
      name: "Solar plexus chakra",
      image: "image/solar.png",
      visualimage: "image/Recraft/Solar/sense-of-sight-elixir.png",
      visualname: "Sense of sight",
      mantra: "Ram",
      audio: "audio/Ram.aac",
      location: "upper abdomen",
      associated:"Sense of Sight, Personal Power, Will power, Self Esteem",
      color: "yellow",
      colorcode: "#FFD700",
      element: "Fire",
      feature: "Willpower",
      description: "The center of our personal power, willpower, and self-esteem",
    },
    {
      name: "Heart chakra",
      image: "image/heart.png",
      visualimage: "image/Recraft/Heart/sense-of-touch-elixir.png",
      visualname: "Sense of touch",
      mantra: "Yam",
      audio: "audio/Yam.aac",
      location: "center of the chest",
      associated:"Sense of touch, Center of our Love, Compassion, Self Esteem",
      color: "green",
      colorcode: "#90EE90",
      element: "Air",
      feature: "Compassion",
      description: "The center of our love, compassion, and forgiveness",
    },
    {
      name: "Throat chakra",
      image: "image/throat.png",
      visualimage: "image/Recraft/Throat/-sense-of-sound-elixir.png",
      visualname: "Sense of hearing",
      mantra: "Ham",
      audio: "audio/Ham.aac",
      location: "throat area",
      associated:"Sense of Hearing, Communication, Self Expression, Truth",
      color: "blue",
      colorcode: "#87CEFF",
      element: "Ether",
      feature: "Communication",
      description: "The center of our communication, self-expression, and truth",
    },
    {
      name: "Third eye chakra",
      image: "image/thirdeye.png",
      visualimage: "image/Recraft/Third-eye/the-sense-of-intuition-elixir.png",
      visualname: "Sense of Intuition",
      mantra: "Om",
      audio: "audio/Om.aac",
      location: "space between the eyebrows",
      associated:"Sense Of intuition, Inner vision, Wisdom, Insight",
      color: "indigo",
      colorcode: "#4B0082",
      element: "Light",
      feature: "Intuition",
      description: "The center of our inner vision, wisdom, and insight",
    },
    {
      name: "Crown chakra",
      image: "image/crown.png",
      visualimage: "image/Recraft/Crown/sense-of-knowing-elixir.png",
      visualname: "Transcendence",
      mantra: "Aum",
      audio: "audio/Aum.aac",
      location: "top of the head",
      associated:"Transcendence, Connection with divine, Higher Consciousness, Enlightenment",
      color: "violet",
      colorcode: "#D8BFD8",
      element: "Thought",
      feature: "Higher Consciousness",
      description: "The center of our connection to the divine, higher consciousness, and enlightenment",
    },
];
