export const chakras = [
  {
    name: "Root Chakra",
    image: "image/root.png",
    visualimage: "image/Recraft/Root/sense-of-smell-smelling-elixir-.png",
    visualname: "Sense of smell",
    mantra: "लं",
    audio: "audio/Lam.aac",
    location: "Base",
    associated:"Sense of Smell, Sense Of Security, Stability, Sense of responsibility",
    color: "red",
    colorcode: "#DC143C",
    element: "Earth",
    feature: "Sense of smell",
    description: "It is believed to be the foundation of our being and is responsible for our sense of security and stability",
  },
  {
      name: "Sacral chakra",
      image: "image/sacral.png",
      visualimage: "image/Recraft/Sacral/sense-of-pleasure-elixir.png",
      visualname: "Sense of sexuality",
      mantra: "वं",
      audio: "audio/Vam.aac",
      location: "below the navel",
      associated:"Sexuality, Sense of taste, Creativity, Emotions",
      color: "orange",
      colorcode: "#FF4500",
      element: "Water",
      feature: "Sense of taste",
      description: "It is believed to be the center of our creativity, sexuality, and emotions",
    },
    {
      name: "Solar plexus chakra",
      image: "image/solar.png",
      visualimage: "image/Recraft/Solar/sense-of-sight-elixir.png",
      visualname: "Sense of sight",
      mantra: "रं",
      audio: "audio/Ram.aac",
      location: "Abdomen",
      associated:"Sense of Sight, Personal Power, Will power, Self Esteem",
      color: "yellow",
      colorcode: "#FFD700",
      element: "Fire",
      feature: "Sense of sight",
      description: "It is believed to be the center of our personal power, willpower, and self-esteem",
    },
    {
      name: "Heart chakra",
      image: "image/heart.png",
      visualimage: "image/Recraft/Heart/sense-of-touch-elixir.png",
      visualname: "Sense of touch",
      mantra: "यं",
      audio: "audio/Yam.aac",
      location: "Chest",
      associated:"Sense of touch, Center of our Love, Compassion, Self Esteem",
      color: "green",
      colorcode: "#90EE90",
      element: "Air",
      feature: "Sense of touch",
      description: "It is believed to be the center of our love, compassion, and forgiveness",
    },
    {
      name: "Throat chakra",
      image: "image/throat.png",
      visualimage: "image/Recraft/Throat/-sense-of-sound-elixir.png",
      visualname: "Sense of hearing",
      mantra: "हं",
      audio: "audio/Ham.aac",
      location: "Throat",
      associated:"Sense of Hearing, Communication, Self Expression, Truth",
      color: "blue",
      colorcode: "#87CEFF",
      element: "Ether",
      feature: "Sense of hearing",
      description: "It is believed to be the center of our communication, self-expression, and truth",
    },
    {
      name: "Third eye chakra",
      image: "image/thirdeye.png",
      visualimage: "image/Recraft/Third-eye/the-sense-of-intuition-elixir.png",
      visualname: "Sense of Intuition",
      mantra: "शं",
      audio: "audio/Om.aac",
      location: "Between the eyebrows",
      associated:"Sense Of intuition, Inner vision, Wisdom, Insight",
      color: "indigo",
      colorcode: "#4B0082",
      element: "light",
      feature: "Sense of intuition",
      description: "It is believed to be the center of our inner vision, wisdom, and insight",
    },
    {
      name: "Crown chakra",
      image: "image/crown.png",
      visualimage: "image/Recraft/Crown/sense-of-knowing-elixir.png",
      visualname: "Transcendence",
      mantra: "ॐ",
      audio: "audio/Aum.aac",
      location: "Top of the head",
      associated:"Transcendence, Connection with divine, Higher Consciousness, Enlightenment",
      color: "violet",
      colorcode: "#D8BFD8",
      element: "thought",
      feature: "Sense of knowing",
      description: "It is believed to be the center of our connection to the divine, higher consciousness, and enlightenment",
    },
];
